language: ruby
dist: trusty
sudo: required
rvm:
  - 2.3.1
branches:
  only:
    - source
  directories:
    - node_modules
cache:
  bundler: true
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: 
    - 178.62.18.237
before_install:
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in deploy-key.enc -out ~/.ssh/id_rsa -d
  - sudo apt-get install python3 python3-pip
  - pip3 install nltk scikit-learn python-frontmatter
  - chmod 600 ~/.ssh/id_rsa
  - nvm install stable
  - npm install
  - npm install --global gulp-cli
script:
  - gulp build --prod
  - bundle exec htmlproofer ./_site --disable-external

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: _site
    target_branch: master
    name: Travis CI
    github_token: "$GITHUB_API_KEY"
    on:
      branch: source
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: source
