language: ruby
rvm:
- 2.3.1


# branch whitelist
branches:
  only:
  - source

cache:
  bundler: true
  directories:
    - node_modules # NPM packages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - nvm install stable
  - npm install

# runs bundle install by default
script:
- gulp build --prod
- bundle exec htmlproofer ./_site --disable-external

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  target_branch: master
  name: "Travis CI"
  github_token: $GITHUB_API_KEY # Set in travis-ci.org dashboard
  on:
    branch: source