title:            "The Confused Me"
description:      "mostly physics and code"
author:           Lingyi Hu
url:              https://theconfused.me # Site url, without a slash at the end.
google_analytics: "UA-96137027-1" # Set tracking, remove from /javascripts/basic.js if unwanted.

plugins:
  - jekyll-paginate-v2
  - jekyll-feed

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true

permalink:        /blog/:title/
defaults:
  - values:
      layout: "default"

exclude: [vendor]
include: [.travis.yml]